version: '3'

services:
  neo4j:
    image: neo4j:enterprise-bullseye
    container_name: neo4j-apoc
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - ${HOME}/neo4j/data:/data
    privileged: true   # 注意Compose对privileged支持有限，仅部分场景有效
    shm_size: 12G      # 设置/dev/shm大小
    deploy:
      resources:
        limits:
          cpus: '32'
          memory: 128G
  ocr-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ppocr
    volumes:
      - ../:/app
      - shared-data:/srv/shared
    ports:
      - 8081:8081
    working_dir: /app
    command: python3 ocr_main.py
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/shared
